/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logoEGS_03.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.001']} position={[0, 0.05, 0]} scale={[15, 1, 15]} />
    </group>
  )
}

useGLTF.preload('/logoEGS_03.glb')
