/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('./logoEGS.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[0, 0.05, 0]} scale={[16.86, 1, 16.86]} />
//       <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.001']} position={[0, 0.05, 0]} scale={[16.86, 1, 16.86]} />
//       <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.001']} position={[0, 0.05, 0]} scale={[16.86, 1, 16.86]} />
//       <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.001']} position={[0, 0.05, 0]} scale={[16.86, 1, 16.86]} />
//       <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.001']} position={[0, 0.05, 0]} scale={[16.86, 1, 16.86]} />
//       <mesh geometry={nodes.Curve005.geometry} material={materials['SVGMat.001']} position={[0, 0.05, 0]} scale={[16.86, 1, 16.86]} />
//     </group>
//   )
// }

// useGLTF.preload('./logoEGS.glb')
